# Generated by Django 4.2.4 on 2023-08-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(upload_to='fotos/assets/'),
        ),
        migrations.CreateModel(
            name='Ensaio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensaios', to='fotos.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='ensaio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='fotos.ensaio'),
        ),
    ]
