# Generated by Django 4.2.4 on 2023-08-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_remove_foto_categoria_alter_foto_imagem_ensaio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='ordem',
        ),
    ]
